name: Infrastructure
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
paths:
  - 'infrastructure/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      LOCATION: eastus
    steps:
      - uses: actions/checkout@v2
        run: bicep build infrastructure/main.bicep
      - uses: Azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - name: Creat resource group
          uses: azure/CLI@v1
          with:
            inlineScript: |
                az group create --location ${{ env.LOCATION }} --name ${{ vars.RESOURCE_GROUP_NAME }}
      - name: Deploy
        run: az deployment sub create --location eastus --template-file infrastructure/main.bicep --name infrastructureDeployment --name ${{ vars.RESOURCE_GROUP_NAME }}
